version: '3'
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  mongodb:
    image: "mongo"
    container_name: mongo
    #ports:
    #  - "27017:27017"
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
  weword-be:
    build: ../weword/be
    container_name: weword-be
    ports:
      - "4001:4001"
      #- "3000:3000"
    depends_on:
      - mongodb
      - redis
    links:
      - mongodb
      - redis
#  weword-fe:
#    build: ../weword/fe
#    container_name: weword-fe
#    links:
#      - weword-be
#    depends_on:
#      - weword-be
#    ports:
#      - "3000:3000"
volumes:
  mongodb:
  mongodb_config:
