version: '3'
services:
  mongodb:
    image: "mongo"
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
  weword-be:
    build: ../weword/be
    container_name: weword-be
    ports:
      - "4001:4001"
    depends_on:
      - mongodb
    links:
      - mongodb
  weword-fe:
    build: ../weword/fe
    container_name: weword-fe
    links:
      - weword-be
    ports:
      - "3000:3000"

volumes:
  mongodb:
  mongodb_config:
